server:
  port: 11000
  servlet:
    session:
      timeout: 30m

spring:
  application:
    name: gulimall-product
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://123.56.166.69:3316/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 123.56.166.69:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  redis:
    host: 123.56.166.69
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 360000
      cache-null-values: true
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
logging:
  level:
    com.lloyvet.gulimall: debug
