server:
  port: 9222
  servlet:
    session:
      timeout: 30m

spring:
  application:
    name: gulimall-search
  cloud:
    nacos:
      discovery:
        server-addr: 123.56.166.69:8848
  thymeleaf:
    cache: false
logging:
  level:
    com.lloyvet.gulimall: debug